import { pgTable, serial, text, integer, real, jsonb, timestamp, boolean } from "drizzle-orm/pg-core";

export const anime = pgTable("anime", {
  id: serial("id").primaryKey(),
  malId: integer("mal_id").unique().notNull(),
  title: text("title").notNull(),
  titleJapanese: text("title_japanese"),
  imageUrl: text("image_url"),
  synopsis: text("synopsis"),
  score: real("score"),
  scoredBy: integer("scored_by"),
  rank: integer("rank"),
  popularity: integer("popularity"),
  episodes: integer("episodes"),
  status: text("status"),
  rating: text("rating"),
  source: text("source"),
  season: text("season"),
  year: integer("year"),
  genres: jsonb("genres"),
  studios: jsonb("studios"),
  airedFrom: timestamp("aired_from"),
  airedTo: timestamp("aired_to"),
  isAiring: boolean("is_airing"),
  trailerUrl: text("trailer_url"),
  type: text("type"),
  members: integer("members"),
  favorites: integer("favorites"),
  duration: text("duration"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});
