import { pgTable, serial, text, integer, real, jsonb, timestamp, boolean } from "drizzle-orm/pg-core";

export const anime = pgTable("anime", {
  id: serial("id").primaryKey(),
  malId: integer("mal_id").unique().notNull(),
  title: text("title").notNull(),
  titleJapanese: text("title_japanese"),
  imageUrl: text("image_url"),
  synopsis: text("synopsis"),
  score: real("score"),
  scoredBy: integer("scored_by"),
  rank: integer("rank"),
  popularity: integer("popularity"),
  episodes: integer("episodes"),
  status: text("status"),
  rating: text("rating"),
  source: text("source"),
  season: text("season"),
  year: integer("year"),
  genres: jsonb("genres").$type<string[] | null>(),
  studios: jsonb("studios").$type<string[] | null>(),
  airedFrom: timestamp("aired_from"),
  airedTo: timestamp("aired_to"),
  isAiring: boolean("is_airing"),
  trailerUrl: text("trailer_url"),
  type: text("type"),
  members: integer("members"),
  favorites: integer("favorites"),
  duration: text("duration"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const manga = pgTable("manga", {
  id: serial("id").primaryKey(),
  malId: integer("mal_id").unique().notNull(),
  title: text("title").notNull(),
  titleJapanese: text("title_japanese"),
  titleEnglish: text("title_english"),
  imageUrl: text("image_url"),
  synopsis: text("synopsis"),
  background: text("background"),
  score: real("score"),
  scoredBy: integer("scored_by"),
  rank: integer("rank"),
  popularity: integer("popularity"),
  chapters: integer("chapters"),
  volumes: integer("volumes"),
  status: text("status"),
  publishing: boolean("publishing"),
  genres: jsonb("genres").$type<string[] | null>(),
  themes: jsonb("themes").$type<string[] | null>(),
  demographics: jsonb("demographics").$type<string[] | null>(),
  authors: jsonb("authors").$type<string[] | null>(),
  serializations: jsonb("serializations").$type<string[] | null>(),
  publishedFrom: timestamp("published_from"),
  publishedTo: timestamp("published_to"),
  type: text("type"),
  members: integer("members"),
  favorites: integer("favorites"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});
