import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/layout/footer";
import MainHeader from "./components/layout/MainHeader";
import Header from "./components/layout/header";
import { ThemeProvider } from "./context/ThemeContext";
import AppWrapper from "./context/AppWrapper"; // <- Importamos o componente separado

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Notícias de Anime - Crunchyroll",
  description: "Generated by create next app",
};

export default function NewsLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <div className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <ThemeProvider>
        <AppWrapper>
          <div className="fixed-header">
            <MainHeader />
          </div>
          <div className="second-header">
            <Header />
          </div>
          <main>{children}</main>
          <footer>
            <Footer />
          </footer>
        </AppWrapper>
      </ThemeProvider>
    </div>
  );
}



